name: "Continuous Deployment - DEV"
on:
  push:
    branches:
      - prueba
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ingsis-team
          password: ${{ secrets.ORG_DOCKER_PACKAGES_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/ingsis-team/ingsis-printscript-ui:latest
          build-args: |
            "USERNAME=${{ secrets.USERNAME }}"
            "TOKEN=${{ secrets.ORG_DOCKER_PACKAGES_SECRET }}"
            "VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE}}"
            "VITE_AUTH0_CLIENT_ID=${{secrets.VITE_AUTH0_CLIENT_ID}}"
            "VITE_AUTH0_DOMAIN=${{secrets.VITE_AUTH0_DOMAIN}}"
            "BACKEND_URL=${{secrets.BACKEND_URL}}"

          push: true